# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e071904b5297d6acb442c458e9d857760b3ba8ba8442ac2033204829b7ddb4fad6be2a83b11850eef4f398dc9906142a72afa8b52fe7cc294d5945f7624592

test:
  secret_key_base: fa3f46ded32e7d6fdf33accf3d8be387030a94c7a4f9cb915f01ef447a74ba4b6198a36efc060efa693b1c6d7ad885c6dfb0d2c446ed9fa465c82dd29629c746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
